#title in header
title: "Hei!"

#main info
#owner
owner: "My name is Erik Peralta LÃ¸vaas"
email: erikpl@protonmail.com
info: "... a Computer Science student and hobby journalist from  ğŸ‡³ğŸ‡´."
#description
desc: ""

#menu
menu:
  # Projects: /Projects (create when relevant)
  Resume: https://read.cv/erikpl
  # About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: EDD519

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
# usercss: css/user.css

# social profile at the footer/bottom
footer: true
github: https://github.com/erikpl
linkedin: https://linkedin.com/in/erikpl

# Misc
nanobar: /js/nanobar.min.js
# switch_light: â˜€ï¸
# switch_dark: ğŸŒ‘

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

# Writing
post_asset_folder: true
